export const winningConfigs = {
  winningSuhaengTopicDb: {
    title: "위닝 수행 주제 DB",
    table: "winning_assessment_knowledge_items",
    searchPlaceholder:
      "학년, 교과군, 진로, 주제 패턴명, 관련 자료를 검색하세요",
    order: "created_at",
    excel: true,
    fixedValues: { knowledge_type: "topic_pattern" },
    columns: [
      { key: "grade", label: "학년" },
      { key: "subject", label: "교과군" },
      { key: "career_field", label: "진로분야" },
      { key: "title", label: "주제 패턴명 / 관련 자료" },
      { key: "source", label: "출처" },
      { key: "is_active", label: "사용", type: "boolean" },
      { key: "created_at", label: "등록일", type: "date" },
    ],
    fields: [
      {
        key: "is_active",
        label: "사용 여부",
        type: "radioBoolean",
        required: true,
      },
      {
        key: "grade",
        label: "학년",
        type: "select",
        options: ["고1", "고2", "고3", "공통", "전체", "확인 필요"],
        required: true,
      },
      {
        key: "subject",
        label: "교과군",
        type: "select",
        options: [
          "국어",
          "수학",
          "영어",
          "사회역사",
          "과학",
          "정보",
          "공통",
          "전체",
          "확인 필요",
        ],
        required: true,
      },
      { key: "career_field", label: "진로분야", type: "text" },
      {
        key: "title",
        label: "주제 패턴명 / 관련 자료",
        type: "text",
        required: true,
      },
      {
        key: "content",
        label: "주제 추천 패턴 내용",
        type: "textarea",
        required: true,
      },
      { key: "source", label: "출처", type: "text" },
      { key: "source_link", label: "출처 링크", type: "text" },
      {
        key: "memo",
        label: "메모",
        type: "textarea",
      },
    ],
    defaults: {
      is_active: true,
      grade: "확인 필요",
      subject: "확인 필요",
      knowledge_type: "topic_pattern",
      career_field: "",
      title: "",
      content: "",
      source: "선배 생기부 PDF / 내부 우수사례",
      source_link: "",
      memo: "",
    },
  },

  winningSuhaengResourceDb: {
    title: "위닝 수행 자료 DB",
    table: "winning_assessment_knowledge_items",
    searchPlaceholder:
      "학년, 교과군, 진로, 실제 자료명, 검색 키워드, 출처를 검색하세요",
    order: "created_at",
    excel: true,
    fixedValues: { knowledge_type: "verified_resource" },
    columns: [
      { key: "grade", label: "학년" },
      { key: "subject", label: "교과군" },
      { key: "career_field", label: "진로분야" },
      { key: "title", label: "실제 자료명 / 검색 키워드" },
      { key: "source", label: "저자·기관·링크·출처" },
      { key: "is_active", label: "사용", type: "boolean" },
      { key: "created_at", label: "등록일", type: "date" },
    ],
    fields: [
      {
        key: "is_active",
        label: "사용 여부",
        type: "radioBoolean",
        required: true,
      },
      {
        key: "grade",
        label: "학년",
        type: "select",
        options: ["고1", "고2", "고3", "공통", "전체", "확인 필요"],
        required: true,
      },
      {
        key: "subject",
        label: "교과군",
        type: "select",
        options: [
          "국어",
          "수학",
          "영어",
          "사회역사",
          "과학",
          "정보",
          "공통",
          "전체",
          "확인 필요",
        ],
        required: true,
      },
      { key: "career_field", label: "진로분야", type: "text" },
      {
        key: "title",
        label: "실제 자료명 / 검색 키워드",
        type: "text",
        required: true,
      },
      {
        key: "content",
        label: "자료 핵심 내용 / 활용 방식 / 주의점",
        type: "textarea",
        required: true,
      },
      {
        key: "source",
        label: "저자·기관·링크·출처 정보",
        type: "text",
      },
      { key: "source_link", label: "출처 링크", type: "text" },
      { key: "memo", label: "메모", type: "textarea" },
    ],
    defaults: {
      is_active: true,
      grade: "확인 필요",
      subject: "확인 필요",
      knowledge_type: "verified_resource",
      career_field: "",
      title: "",
      content: "",
      source: "",
      source_link: "",
      memo: "",
    },
  },

  winningSetukDb: {
    title: "위닝 세특 DB",
    comingSoon: true,
    description:
      "추후 별도 Supabase와 연동 예정입니다. 현재는 메뉴명만 선반영했습니다.",
  },

  winningDeepReportDb: {
    title: "위닝 심화보고서 DB",
    comingSoon: true,
    description:
      "추후 별도 Supabase와 연동 예정입니다. 현재는 메뉴명만 선반영했습니다.",
  },

  winningStudentRecordDb: {
    title: "위닝 생기부 DB",
    table: "winning_assessment_knowledge_items",
    searchPlaceholder: "학년, 교과군, 진로, 생기부 패턴, 자료명을 검색하세요",
    order: "created_at",
    excel: true,
    fixedValues: { knowledge_type: "student_record_pattern" },
    columns: [
      { key: "grade", label: "학년" },
      { key: "subject", label: "교과군" },
      { key: "career_field", label: "진로분야" },
      { key: "title", label: "사례명" },
      { key: "source", label: "출처/원본" },
      { key: "is_active", label: "사용", type: "boolean" },
      { key: "created_at", label: "등록일", type: "date" },
    ],
    fields: [
      {
        key: "is_active",
        label: "사용 여부",
        type: "radioBoolean",
        required: true,
      },
      {
        key: "grade",
        label: "학년",
        type: "select",
        options: ["고1", "고2", "고3", "공통", "전체", "확인 필요"],
        required: true,
      },
      {
        key: "subject",
        label: "교과군",
        type: "select",
        options: [
          "국어",
          "수학",
          "영어",
          "사회역사",
          "과학",
          "공통",
          "전체",
          "확인 필요",
        ],
        required: true,
      },
      { key: "career_field", label: "진로분야", type: "text" },
      { key: "title", label: "사례명", type: "text", required: true },
      {
        key: "content",
        label: "생기부 패턴 텍스트",
        type: "textarea",
        required: true,
      },
      { key: "source", label: "출처/원본 파일명", type: "text" },
      { key: "source_link", label: "출처 링크", type: "text" },
      { key: "memo", label: "메모", type: "textarea" },
    ],
    defaults: {
      is_active: true,
      grade: "확인 필요",
      subject: "확인 필요",
      knowledge_type: "student_record_pattern",
      career_field: "",
      title: "",
      content: "",
      source: "선배 생기부 PDF / 내부 우수사례",
      source_link: "",
      memo: "",
    },
  },

  winningBaseData: {
    title: "기초데이터추출",
    table: "winning_base_data",
    searchPlaceholder: "자료명을 검색하세요",
    order: "sort_order",
    excel: true,
    columns: [
      { key: "data_type", label: "자료구분" },
      { key: "title", label: "자료명" },
      { key: "source", label: "출처" },
      { key: "is_active", label: "사용", type: "boolean" },
    ],
    fields: [
      {
        key: "is_active",
        label: "사용 여부",
        type: "radioBoolean",
        required: true,
      },
      { key: "data_type", label: "자료구분", type: "text" },
      { key: "title", label: "자료명", type: "text", required: true },
      { key: "source", label: "출처", type: "text" },
      { key: "content", label: "내용", type: "textarea" },
      { key: "memo", label: "메모", type: "textarea" },
      { key: "sort_order", label: "순서", type: "number" },
    ],
    defaults: {
      is_active: true,
      data_type: "",
      title: "",
      content: "",
      source: "",
      sort_order: 1,
    },
  },

  winningDbInputs: {
    title: "위닝DB입력",
    table: "winning_db_inputs",
    searchPlaceholder: "입력 자료명을 검색하세요",
    order: "created_at",
    excel: true,
    columns: [
      { key: "input_type", label: "입력구분" },
      { key: "title", label: "자료명" },
      { key: "memo", label: "메모" },
      { key: "created_at", label: "등록일", type: "date" },
    ],
    fields: [
      { key: "input_type", label: "입력구분", type: "text" },
      { key: "title", label: "자료명", type: "text", required: true },
      { key: "raw_data", label: "원본 데이터", type: "textarea" },
      { key: "memo", label: "메모", type: "textarea" },
    ],
    defaults: { input_type: "", title: "", raw_data: "", memo: "" },
  },
};
