-- QA 행301 — 학습방향 리포트(#37 내신 / #38 정시) 저장 + 이력(신규 테이블)
--
-- 왜
--   지금 api/goal/report.ts type=direction 은 조회 때마다 즉석 계산만 하고 아무것도
--   저장하지 않는다 — "시험별 리포트 생성·이력" 요구(QA 행301)를 채우려면 회차별로
--   생성한 리포트 스냅샷이 남아야 한다. goal_daily_records 처럼 자체 profile_id
--   테이블로 둔다(학생 이력이 늘어나는 append-only 성격이 같다).
--
-- 정본 참고
--   원본 target 테이블 learning_direction_reports(target-app-analysis.md §2.10) —
--   source_type/source_label/report_kind/report_payload/naesin_snapshot/jungsi_snapshot
--   컬럼 구성을 그대로 따르되, kind별 스냅샷 컬럼 2개를 단일 jsonb snapshot 하나로
--   합친다(우리 테이블은 kind 컬럼으로 이미 내신/정시가 갈리므로 kind별 컬럼을
--   따로 둘 필요가 없다 — 원본은 한 행에 두 kind를 같이 만들었지만 우리 빌더는
--   kind 하나당 행 하나다).
--
-- unique(profile_id, kind, source_type, source_label)
--   같은 학생·같은 종류(kind)·같은 트리거(source_type)·같은 출처 라벨(예: 회차명)이면
--   재생성 시 새 행을 쌓지 않고 덮어쓴다(upsert) — 같은 시험을 다시 입력했을 때
--   이력이 무한정 늘어나지 않게 하기 위함(api/goal/grades.ts upsertRecord의
--   "같은 term=교체" 관례와 같은 판단).

CREATE TABLE IF NOT EXISTS "public"."goal_direction_reports" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "profile_id" "uuid" NOT NULL REFERENCES "public"."goal_students"("profile_id") ON DELETE CASCADE,
    "source_type" "text" NOT NULL,
    "source_label" "text" NOT NULL,
    "kind" "text" NOT NULL,
    "payload" "jsonb" NOT NULL,
    "snapshot" "jsonb" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "goal_direction_reports_source_type_check" CHECK (("source_type" = ANY (ARRAY['intake'::"text", 'naesin'::"text", 'mogo'::"text"]))),
    CONSTRAINT "goal_direction_reports_kind_check" CHECK (("kind" = ANY (ARRAY['naesin'::"text", 'jungsi'::"text"])))
);

ALTER TABLE "public"."goal_direction_reports" OWNER TO "postgres";

CREATE UNIQUE INDEX IF NOT EXISTS "goal_direction_reports_identity_key"
  ON "public"."goal_direction_reports" ("profile_id", "kind", "source_type", "source_label");

CREATE INDEX IF NOT EXISTS "goal_direction_reports_profile_kind_created_idx"
  ON "public"."goal_direction_reports" ("profile_id", "kind", "created_at" DESC);

COMMENT ON TABLE "public"."goal_direction_reports" IS '학습방향 리포트(#37 내신 / #38 정시) 생성·저장 이력(QA 행301). 원본 target learning_direction_reports 대응(target-app-analysis.md §2.10) — kind별 스냅샷 컬럼을 snapshot 하나로 합친 점만 다르다. 생성 시점 3곳: (a) 온보딩 성공 시 kind별 1건(source_type=intake, source_label=''내 현재 위치''), (b) api/goal/grades.ts POST 성공 시 해당 kind 1건(source_type=naesin|mogo, source_label=시험 라벨), (c) 저장 리포트 0건인 기존 학생의 GET 조회 시 lazy 생성. 쓰기는 service_role(api/_lib/goalDirectionReport.ts 호출부)만.';

COMMENT ON COLUMN "public"."goal_direction_reports"."profile_id" IS 'goal_students.profile_id(≡auth.users.id). 소유자 판정은 언제나 세션 토큰에서 얻은 profileId로만 한다(api/_lib/goalRepo.ts openGoalSession 관례).';

COMMENT ON COLUMN "public"."goal_direction_reports"."source_type" IS '생성 트리거. intake=온보딩 직후, naesin=api/goal/grades.ts 내신 성적 저장, mogo=api/goal/grades.ts 모의고사 성적 저장. 원본 CHECK 도메인 그대로(target-app-analysis.md §2.10 source_type 열).';

COMMENT ON COLUMN "public"."goal_direction_reports"."source_label" IS '표시용 출처 라벨 — intake는 ''내 현재 위치'' 고정, naesin/mogo는 해당 회차의 term(예: ''고3 6월 모의고사''). 회차 칩(periodChips) 표시 문자열이자 (profile_id, kind, source_type, source_label) 유일 식별자의 일부다.';

COMMENT ON COLUMN "public"."goal_direction_reports"."kind" IS '리포트 종류. naesin=#37 내신 탭, jungsi=#38 정시 탭.';

COMMENT ON COLUMN "public"."goal_direction_reports"."payload" IS 'LearningDirectionReportPayload 전문(jsonb) — scaleMax/overallAverage/subjectAverage[]/studentType/subjectReports[](피라미드 레벨·방향 문구·추천 교재 포함). api/_lib/goalDirectionReport.ts buildGoalDirectionReport()의 반환값을 그대로 저장한다(GET 응답이 그대로 되돌려준다).';

COMMENT ON COLUMN "public"."goal_direction_reports"."snapshot" IS '생성 당시 입력 원본(jsonb) — 재현·감사용. naesin_scores.groupAverages 또는 legacy 회차 엔트리(mock_exam_scores.rounds 또는 records[]) 중 실제로 쓰인 것을 그대로 담는다. 원본 naesin_snapshot/jungsi_snapshot 두 컬럼을 kind로 이미 갈리는 이 테이블에서는 하나로 합쳤다.';

COMMENT ON COLUMN "public"."goal_direction_reports"."created_at" IS '리포트 생성 시각 — 회차 칩 정렬(최신순) 키.';

ALTER TABLE "public"."goal_direction_reports" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "goal_direction_reports_select_own" ON "public"."goal_direction_reports" FOR SELECT TO "authenticated" USING (("profile_id" = "auth"."uid"()));

CREATE POLICY "goal_direction_reports_admin_select" ON "public"."goal_direction_reports" FOR SELECT TO "authenticated" USING ("public"."is_winning_admin"());

GRANT ALL ON TABLE "public"."goal_direction_reports" TO "anon";
GRANT ALL ON TABLE "public"."goal_direction_reports" TO "authenticated";
GRANT ALL ON TABLE "public"."goal_direction_reports" TO "service_role";
