-- =====================================================================
-- 47_premium_book.sql
-- 이용신청 > 프리미엄 이용 : 책자 페이지 (premium_book_pages)
-- Supabase SQL Editor에서 수동 실행 필요 (이 repo에 마이그레이션 러너
-- 없음 — 00~46번과 동일하게 파일 전체를 붙여넣고 실행한다).
-- idempotent — 여러 번 실행해도 안전.
--
-- 이 파일은 책자 테이블 하나만 다룬다. 상담 신청
-- (premium_consult_requests, PII)은 sql/48_premium_consult.sql로
-- 이월했다 — §8 #3(개인정보 보유 기간) 확정 전에는 작성·실행 금지.
--
-- ---------------------------------------------------------------------
-- 설계 메모
-- ---------------------------------------------------------------------
-- sort_order 가 페이지 번호 겸 정렬 키인 단일 축이다. page_no(UNIQUE)를
-- 따로 두지 않는다 — 같은 축을 둘 다 어드민에서 편집 가능하게 두면
-- 드리프트가 시간문제인 데다 판정 규칙이 없다.
--
-- sort_order 에 UNIQUE를 걸지 않는다. 어드민에서 번호를 직접 바꿔
-- 재배치하는 사용(3번↔4번 맞바꾸기 등)을 임시값 경유 없이 살리기 위한
-- 결정이다. 그 덕에 어드민 폼의 상수 default(sort_order = 1)도 안전하다
-- — UNIQUE가 있던 시절엔 default가 있어도 두 번째 등록부터 23505로
-- 막혔다. 중복은 DB가 아니라 어드민 목록의 경고 배너로 알린다.
--
-- is_active 를 두지 않는다. 중간 1장 숨김이 spread(펼침면) 페어링을
-- 조용히 밀어버린다. 요구는 "재업로드·관리"이지 개별 숨김이 아니다.
-- alt_text 도 두지 않는다 — 프론트에서 `프리미엄 안내 책자 N페이지`로
-- 생성해 동일 실익을 낸다.
--
-- RLS는 is_winning_admin() 기준. profiles 직접 서브쿼리는 42P17
-- infinite recursion 으로 관리자 쓰기가 전부 막히므로 반드시
-- public.is_winning_admin()(00_base_schema.sql:1330)을 통해 판정한다
-- (43·44번과 동일 패턴).
-- =====================================================================

-- ---------------------------------------------------------------------
-- (1) 책자 페이지 테이블
-- ---------------------------------------------------------------------
create table if not exists public.premium_book_pages (
    id bigint generated by default as identity primary key,

    sort_order integer     not null default 1,   -- 페이지 번호 겸 정렬 키 (단일 축, UNIQUE 없음)
    image_url  text        not null default '',

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------
-- (2) 인덱스 — 정렬 조회용 일반 인덱스. UNIQUE 아님(위 설계 메모 참고).
-- ---------------------------------------------------------------------
create index if not exists premium_book_pages_sort_order_idx
    on public.premium_book_pages using btree (sort_order);

-- ---------------------------------------------------------------------
-- (3) RLS
-- ---------------------------------------------------------------------
alter table public.premium_book_pages enable row level security;

drop policy if exists "premium_book_pages_public_read" on public.premium_book_pages;
create policy "premium_book_pages_public_read" on public.premium_book_pages
    as permissive for select to anon, authenticated
    using (true);

drop policy if exists "premium_book_pages_admin_all" on public.premium_book_pages;
create policy "premium_book_pages_admin_all" on public.premium_book_pages
    as permissive for all to public
    using (public.is_winning_admin())
    with check (public.is_winning_admin());

-- ---------------------------------------------------------------------
-- (4) updated_at 트리거 — 저장소 공용 함수 재사용
--     (00_base_schema.sql:1424 public.set_updated_at(), admin_* /
--     banners / galleries 등 다수 테이블이 이미 쓰는 관례).
--     새 함수를 만들지 않는다.
-- ---------------------------------------------------------------------
drop trigger if exists set_premium_book_pages_updated_at on public.premium_book_pages;
create trigger set_premium_book_pages_updated_at
    before update on public.premium_book_pages
    for each row execute function public.set_updated_at();

-- =====================================================================
-- 실행 후 눈으로 확인할 쿼리 (주석 해제하고 수동 실행)
--
-- 이 파일에는 자동 검증 블록을 두지 않는다. premium_book_pages 는
-- public read 가 의도된 설계라 "anon/authenticated 권한 0행"류 검증이
-- 애초에 성립하지 않고, 상담 테이블(sql/48)의 grant 검증 쿼리를 실수로
-- 여기 복사하면 아직 존재하지 않는 premium_consult_requests 에 대해
-- 조용히 0행을 반환해 "테이블이 없어서 0행"을 "정책이 안전해서 0행"으로
-- 오독하게 된다 — 무증상 통과다. 검증 블록은 sql/48 에만 둔다.
-- =====================================================================
-- select count(*) from public.premium_book_pages;
-- select indexname from pg_indexes where tablename = 'premium_book_pages';           -- premium_book_pages_sort_order_idx 가 UNIQUE가 아니어야 정상
-- select policyname, cmd, roles from pg_policies where tablename = 'premium_book_pages'; -- public_read(select) / admin_all(all) 2행
-- select tgname from pg_trigger where tgrelid = 'public.premium_book_pages'::regclass and not tgisinternal; -- set_premium_book_pages_updated_at

-- ---------------------------------------------------------------------
-- Storage 메모 (스키마 변경 없음 — 참고용)
--
-- 페이지 이미지와 원본 PDF는 모두 기존 'banners' 버킷을 재사용한다
-- (Admin.jsx 의 IMAGE_BUCKET 하드코딩, sql/31_storage_policies.sql).
--   - 페이지 이미지: folder 'premium-book' + 랜덤 파일명(기존 업로드 규칙)
--   - 원본 PDF: 결정적 고정 경로 'premium-book/booklet.pdf' 에 upsert
--     덮어쓰기. 경로 자체가 스키마이므로 DB 컬럼을 두지 않는다.
--
-- sql/31_storage_policies.sql 은 storage.buckets 를 (id, name, public)
-- 3컬럼으로만 다뤄 file_size_limit / allowed_mime_types 를 설정한 적이
-- 없다. 대용량 application/pdf 업로드가 현재 'banners' 버킷 설정을
-- 통과하는지 확인된 이력이 없으므로 원본 PDF 보관 착수 전에 실측이
-- 필요하다. 조치가 필요하면 allowed_mime_types 전체 해제가 아니라
-- 'application/pdf' 1종 추가로 한정한다.
-- ---------------------------------------------------------------------
