-- =====================================================================
-- 48_premium_consult.sql
-- 이용신청 > 프리미엄 이용 : 상담 신청 (premium_consult_requests)
-- Supabase SQL Editor에서 수동 실행 필요 (이 repo에 마이그레이션 러너
-- 없음 — 00~47번과 동일하게 파일 전체를 붙여넣고 실행한다).
-- idempotent — 여러 번 실행해도 안전.
--
-- 47번(premium_book_pages)에서 이월된 PII 테이블이다. §8 #3(개인정보
-- 보유 기간) 확정에 따라 이제 작성한다.
--
-- ---------------------------------------------------------------------
-- 개인정보 보유기간
-- ---------------------------------------------------------------------
-- 개인정보처리방침 「4. 보유 및 이용기간」의 전화콜멘토서비스 항목과
-- 동일하게 상담 종료 후 2년을 적용한다. 자동 삭제 잡은 이번 범위가
-- 아니다 — 기간 경과 후 삭제는 운영자가 어드민에서 수동으로 처리한다.
--
-- ---------------------------------------------------------------------
-- 설계 메모
-- ---------------------------------------------------------------------
-- anon/authenticated insert 정책을 두지 않는다. 신청 저장은
-- api/create-consult-request.js(service_role, RLS 우회)만 담당한다.
-- Supabase Data API 자체에는 요청 제한이 없어서, insert를 anon에게
-- 열면 스팸 유입을 DB 레이어에서 막을 수단이 없어진다. rate limit·
-- 화이트리스트 검증은 전부 서버 함수 쪽에서 한다.
--
-- RLS는 is_winning_admin() 기준. profiles 직접 서브쿼리는 42P17
-- infinite recursion 으로 관리자 쓰기가 전부 막히므로 반드시
-- public.is_winning_admin()(00_base_schema.sql:1330)을 통해 판정한다
-- (43·44·47번과 동일 패턴).
-- =====================================================================

-- ---------------------------------------------------------------------
-- (1) 상담 신청 테이블
-- ---------------------------------------------------------------------
create table if not exists public.premium_consult_requests (
    id           bigint      generated by default as identity primary key,

    name         text        not null,
    phone        text        not null,
    email        text        not null default '',
    service      text        not null default '',
    message      text        not null default '',
    status       text        not null default 'new',
    admin_note   text        not null default '',

    created_at   timestamptz not null default now(),
    updated_at   timestamptz not null default now(),

    constraint premium_consult_requests_status_check
        check (status in ('new', 'contacted', 'done', 'cancelled'))
);

-- ---------------------------------------------------------------------
-- (2) 인덱스 — 어드민 목록의 최신순 정렬 조회용.
-- ---------------------------------------------------------------------
create index if not exists premium_consult_requests_created_at_idx
    on public.premium_consult_requests using btree (created_at desc);

-- ---------------------------------------------------------------------
-- (3) RLS — 어드민 전용 하나만. anon/authenticated insert 정책 없음
--     (위 설계 메모 참고).
-- ---------------------------------------------------------------------
alter table public.premium_consult_requests enable row level security;

drop policy if exists "premium_consult_requests_admin_all" on public.premium_consult_requests;
create policy "premium_consult_requests_admin_all" on public.premium_consult_requests
    as permissive for all to public
    using (public.is_winning_admin())
    with check (public.is_winning_admin());

-- ---------------------------------------------------------------------
-- (4) updated_at 트리거 — 저장소 공용 함수 재사용
--     (00_base_schema.sql:1424 public.set_updated_at(), 47번과 동일 관례).
--     새 함수를 만들지 않는다.
-- ---------------------------------------------------------------------
drop trigger if exists set_premium_consult_requests_updated_at on public.premium_consult_requests;
create trigger set_premium_consult_requests_updated_at
    before update on public.premium_consult_requests
    for each row execute function public.set_updated_at();
