-- =====================================================================
-- 74_goal_schedules.sql
-- 목표관리(/app/goal) 중요일정(수행평가/시험/제출마감/기타) 데이터 레이어.
-- Supabase SQL Editor / Management API에서 수동 실행 필요.
-- 선행: sql/55_goal_management.sql (goal_students, public.set_updated_at()).
-- idempotent — 여러 번 실행해도 안전.
--
-- 배경 — docs/figma-goal/resurvey/2910-3939-*.md(중요일정 목록·D-day), 2910-4049-*.md
-- (일정 등록/수정 모달). UI(Schedules.jsx, ScheduleListCard.jsx, AddSchedule*Modal.jsx,
-- 대시보드 ScheduleRail, 사이드바 카운트 뱃지)는 이미 완성돼 있고 mockSchedules(goalMock.js)
-- + console.log 스텁 상태다. 이 파일은 그 배선의 저장소만 제공한다.
--
-- 학생당 다건이라 goal_students(사용자당 1행)와 달리 대리 키(id)를 PK로 쓴다.
-- 쓰기 정책은 두지 않는다 — sql/55 goal_students/goal_daily_records/goal_probability_logs
-- 3종과 동일한 이유다: service_role을 쓰는 api/goal/schedules.js가 유일한 쓰기 경로다.
--
-- 주의:
--   - admin 판정은 public.is_winning_admin()을 쓴다(is_admin() 아님, sql/55 관례).
--   - `revoke ... from anon, authenticated`는 걸지 않는다 — 테이블 권한이 RLS보다
--     먼저 평가돼 어드민 조회까지 막힌다(sql/52·46이 기록한 기각 사유).
--   - `force row level security`도 쓰지 않는다(sql/55 관례 — SECURITY DEFINER 함수가
--     RLS를 면제받는 조합을 force가 깨뜨린다).
-- =====================================================================


-- ---------------------------------------------------------------------
-- (1) 중요일정 — 학생당 다건
-- ---------------------------------------------------------------------
create table if not exists public.goal_schedules (
    id bigint generated by default as identity primary key,
    profile_id uuid not null references public.goal_students(profile_id) on delete cascade,

    title text not null,
    -- 시안 4종 고정값(AddScheduleFullModal.jsx goalModalOptions.scheduleTypes와
    -- 순서·의미 1:1): performance=수행평가, exam=시험, deadline=제출마감, etc=기타.
    category text not null,
    due_date date not null,
    memo text not null default '',

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint goal_schedules_category_check
        check (category in ('performance', 'exam', 'deadline', 'etc')),
    -- 트림 후 1~100자. 빈 문자열·공백만 있는 제목을 막는다(등록 모달의
    -- `title.trim().length > 0` 클라이언트 검증을 DB 레벨에서도 강제).
    constraint goal_schedules_title_check
        check (char_length(btrim(title)) between 1 and 100)
);

comment on table public.goal_schedules is
    '목표관리 중요일정(수행평가/시험/제출마감/기타). 학생당 다건. 쓰기는 service_role(api/goal/schedules.js)만, 읽기는 본인과 어드민. sql/74_goal_schedules.sql 참고.';

comment on column public.goal_schedules.profile_id is
    'goal_students.profile_id. 학생 탈퇴(auth.users 삭제 → goal_students cascade) 시 함께 삭제된다.';
comment on column public.goal_schedules.title is
    '일정 이름. 트림 1~100자(goal_schedules_title_check).';
comment on column public.goal_schedules.category is
    '일정 종류. 값 4종 고정 — 화면 라벨은 서버(api/goal/schedules.js)가 매핑한다(performance→수행평가 등).';
comment on column public.goal_schedules.due_date is
    '마감일(실제 캘린더 날짜). D-day 표시는 클라이언트가 오늘(KST) 기준으로 매번 계산한다 — 이 컬럼에는 저장하지 않는다.';
comment on column public.goal_schedules.memo is
    '자유 메모(선택). 빈 문자열 허용.';
comment on column public.goal_schedules.updated_at is
    '마지막 갱신 시각. 트리거 trg_goal_schedules_updated_at 이 공용 public.set_updated_at()(00_base_schema.sql:1432)으로 채운다.';

-- 목록 조회(GET /api/goal/schedules)와 대시보드 레일(가까운 순 3건)이 공유하는 정렬 축.
create index if not exists goal_schedules_profile_due_idx
    on public.goal_schedules (profile_id, due_date);


-- ---------------------------------------------------------------------
-- (2) RLS — sql/55_goal_management.sql (6-2) goal_daily_records 관례 그대로.
--     클라이언트는 본인 행 읽기만 가능하다. 쓰기 정책은 두지 않는다.
-- ---------------------------------------------------------------------
alter table public.goal_schedules enable row level security;

drop policy if exists "goal_schedules_select_own" on public.goal_schedules;
create policy "goal_schedules_select_own" on public.goal_schedules
    as permissive for select to authenticated
    using (profile_id = auth.uid());

drop policy if exists "goal_schedules_admin_all" on public.goal_schedules;
create policy "goal_schedules_admin_all" on public.goal_schedules
    as permissive for all to authenticated
    using (public.is_winning_admin())
    with check (public.is_winning_admin());


-- ---------------------------------------------------------------------
-- (3) updated_at 트리거 — 저장소 공용 함수 재사용(00_base_schema.sql:1432).
-- ---------------------------------------------------------------------
drop trigger if exists trg_goal_schedules_updated_at on public.goal_schedules;
create trigger trg_goal_schedules_updated_at
    before update on public.goal_schedules
    for each row execute function public.set_updated_at();


-- =====================================================================
-- 검증용 SELECT (실행 후 수동 확인용 — 주석 해제하고 실행)
-- =====================================================================
-- select table_name from information_schema.tables
--   where table_schema = 'public' and table_name = 'goal_schedules';
--
-- select count(*) from public.goal_schedules;   -- 신규 테이블이므로 0행이 정상
--
-- select tablename, policyname, cmd, roles from pg_policies
--   where schemaname = 'public' and tablename = 'goal_schedules'
--   order by policyname;   -- 정책 2건
--
-- select relname, relrowsecurity, relforcerowsecurity from pg_class
--   where relnamespace = 'public'::regnamespace and relname = 'goal_schedules';
--
-- select conname, pg_get_constraintdef(oid) from pg_constraint
--   where conrelid = 'public.goal_schedules'::regclass order by conname;


-- =====================================================================
-- 되돌리기(롤백) — 실행하지 마라. 필요할 때만 수동으로 복사해서 쓴다.
-- ⚠ 학생 데이터가 들어간 뒤에는 되돌리지 마라 — 복구 수단이 없다.
-- =====================================================================
-- drop trigger if exists trg_goal_schedules_updated_at on public.goal_schedules;
-- -- public.set_updated_at() 은 공용 함수라 절대 drop 하지 마라.
-- drop policy if exists "goal_schedules_admin_all"  on public.goal_schedules;
-- drop policy if exists "goal_schedules_select_own" on public.goal_schedules;
-- drop table if exists public.goal_schedules;
