-- =====================================================================
-- 75_goal_plan_tasks.sql
-- 목표관리(/app/goal) 학습 계획(오늘 계획 + 주간 계획표) 데이터 레이어.
-- Supabase SQL Editor / Management API에서 수동 실행 필요.
-- (이 repo에 마이그레이션 러너 없음 — 00~72번과 동일하게 파일 전체를
--  붙여넣고 실행한다.)  idempotent — 여러 번 실행해도 안전.
--
-- 포함:
--   1) public.goal_plan_tasks   요일별 학습 과제(주간 계획표 컬럼 + 대시보드
--                                "오늘 학습 계획" 레일이 공유하는 단일 테이블)
--   2) RLS — select own + admin all(쓰기는 client 정책 0건, service_role 전용)
--   3) updated_at 트리거(공용 public.set_updated_at() 재사용)
--
-- 배경(임무 지시 "단계 E: 학습 계획 백엔드 + 배선"):
--  - UI는 이미 완성돼 있다 — src/pages/goal/WeeklyPlan.jsx(주간 계획표) +
--    src/components/goal/dashboard/StudyPlanRail.jsx(대시보드 "OO요일 나의
--    학습 계획하기" 레일) + src/components/goal/modals/AddTaskModal.jsx(과제
--    추가 모달). 전부 mockWeeklyPlan/mockTodayPlan(src/data/goalMock.js) +
--    console.log 스텁이었다. 이 파일이 그 목업을 대체하는 실 테이블이다.
--  - 원본 외부 앱(target)에는 이 기능이 없다 — goal_students/goal_daily_records
--    (sql/55_goal_management.sql)처럼 역산할 원본 스키마가 없는 신규 기능이다.
--    그래서 컬럼 코멘트에 원본 참조가 없다.
--  - 용어는 "과제"로 확정했다(AddTaskModal.jsx 「과제 추가」, WeekdayPlanBoard.jsx
--    「+ 추가」 버튼과 카드가 그리는 항목 전부 이 명칭이다).
--  - "일정(오늘만/이번 주만/매주 반복)" — AddTaskModal의 실 필드(ModalField
--    'schedule')다. 이 테이블에는 반복 규칙 컬럼을 두지 않는다 — plan_date가
--    정본이고, "이번 주만/매주 반복"은 클라이언트가 대상 주의 요일마다 각각
--    1행씩 만드는 것으로 구현한다(api/goal/plan-tasks.js는 단건 CRUD만 안다).
--    반복 예약(미래 주까지 자동 생성)은 이번 범위 밖이다 — 필요해지면 별도
--    recurrence 테이블/컬럼으로 확장한다(이 파일은 그 여지를 막지 않는다).
--
-- 의존성:
--   - 00_base_schema.sql : public.is_winning_admin()(1338행),
--                          public.set_updated_at()(1432행)
--   - sql/55_goal_management.sql : public.goal_students(profile_id) FK 대상
--   위 셋만 있으면 다른 마이그레이션과 독립 실행 가능하다.
--   **api/goal/plan-tasks.js 배포 전 반드시 선행 실행** — 테이블 없이
--   배포하면 학습 계획 저장이 전량 실패한다.
--
-- 주의:
--   - admin 판정은 반드시 public.is_winning_admin()을 쓴다(is_admin() 아님,
--     42P17 infinite recursion 회피 — README 「RLS admin 판정」).
--   - `revoke ... from anon, authenticated` 는 걸지 않는다(52번:23-28 근거,
--     55번 헤더 동일 관례).
--   - `force row level security` 도 쓰지 않는다(README:29).
--   - subject는 CHECK 5종('korean'|'math'|'english'|'science'|'etc')이다.
--     AddTaskModal 과목 칩은 한글 라벨(국어/수학/영어/탐구/기타,
--     goalModalOptions.taskSubjects, goalMock.js:296)을 쓴다 — 코드값
--     매핑(SUBJECT_CODE_TO_LABEL)은 api/_lib/goalRepo.js가 담당한다.
-- =====================================================================


-- ---------------------------------------------------------------------
-- (1) 학습 계획 과제
--     CHECK 제약은 create table 안에 인라인으로 둔다(43/52/55번 관례).
-- ---------------------------------------------------------------------
create table if not exists public.goal_plan_tasks (
    id bigint generated by default as identity primary key,
    profile_id uuid not null references public.goal_students(profile_id) on delete cascade,

    -- 과제가 배정된 날짜(실제 달력 날짜). goal_daily_records.record_date와 달리
    -- "가상 날짜"가 아니다 — 학습 계획은 실제 요일·주차 개념이라 실제 달력을 쓴다.
    plan_date date not null,

    -- 과제 내용. AddTaskModal "할 일" 필드(placeholder "예) 미적분 3단원 문제 30개").
    title text not null,

    -- 과목. AddTaskModal 과목 칩 5종의 코드값(한글 라벨은 API 계층에서 왕복 변환).
    subject text not null,

    -- 예상 소요 시간(분). AddTaskModal "예상 소요 시간" 셀렉트(30분~3시간)를
    -- 분 단위로 환산해 저장한다(src/lib/goalPlanUtils.js durationLabelToMinutes).
    duration_minutes integer not null default 0,

    -- 완료 여부. 대시보드 레일의 체크(✓) 액션이 토글한다.
    done boolean not null default false,

    -- 같은 날짜 안에서의 표시 순서. 기본값 0 — 이번 범위는 드래그 재정렬이 없어
    -- 전부 0으로 저장되고 생성 순(id)으로 보이지만, 컬럼을 미리 둬 재정렬 기능이
    -- 추가될 때 마이그레이션 없이 확장 가능하게 한다.
    sort_order integer not null default 0,

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint goal_plan_tasks_title_check
        check (char_length(title) between 1 and 100),
    constraint goal_plan_tasks_subject_check
        check (subject in ('korean', 'math', 'english', 'science', 'etc')),
    constraint goal_plan_tasks_duration_minutes_check
        check (duration_minutes >= 0)
);

comment on table public.goal_plan_tasks is
    '목표관리 학습 계획 과제 — 주간 계획표(WeeklyPlan.jsx)와 대시보드 "오늘 학습 계획" 레일(StudyPlanRail.jsx)이 공유하는 단일 테이블. 원본 외부 앱(target)에 대응 테이블 없음(신규 기능). 쓰기는 service_role(api/goal/plan-tasks.js)만. sql/75_goal_plan_tasks.sql 참고.';

comment on column public.goal_plan_tasks.profile_id is
    'goal_students.profile_id(≡auth.users.id). 소유자 판정은 언제나 세션 토큰에서 얻은 profileId로만 한다(api/_lib/goalRepo.js openGoalSession 관례) — 클라이언트가 보낸 어떤 id도 신뢰하지 않는다.';
comment on column public.goal_plan_tasks.plan_date is
    '과제가 배정된 실제 달력 날짜(YYYY-MM-DD). goal_daily_records.record_date(가상 날짜)와 무관한 별개 개념이다.';
comment on column public.goal_plan_tasks.title is
    '과제 내용(자유 입력). 길이 제약은 AddTaskModal 폼에 명시적 max가 없어 방어적으로 100자로 둔다.';
comment on column public.goal_plan_tasks.subject is
    '과목 코드 5종. 한글 라벨(국어/수학/영어/탐구/기타)과의 매핑은 api/_lib/goalRepo.js SUBJECT_CODE_TO_LABEL/SUBJECT_LABEL_TO_CODE가 담당한다 — DB에는 코드값만 저장한다.';
comment on column public.goal_plan_tasks.duration_minutes is
    '예상 소요 시간(분). AddTaskModal "예상 소요 시간" 셀렉트 라벨(예: "1시간 30분")을 분으로 환산한 값 — 라벨 자체는 저장하지 않는다.';
comment on column public.goal_plan_tasks.done is
    '완료 여부. 대시보드 레일 체크(✓) 액션이 PUT으로 토글한다. 원본 mockTodayPlan의 3상태(done/fail/pending) 중 fail은 이 스키마에 대응 컬럼이 없다 — ✕ 액션은 "미달성 표시"가 아니라 DELETE(과제 삭제)로 구현한다(임무 지시 배선 절 판단 기록).';
comment on column public.goal_plan_tasks.sort_order is
    '같은 plan_date 안에서의 표시 순서. 이번 범위는 항상 0(재정렬 UI 없음) — 컬럼만 선점해 둔다.';
comment on column public.goal_plan_tasks.created_at is
    '행 생성 시각.';
comment on column public.goal_plan_tasks.updated_at is
    '마지막 갱신 시각. 트리거 trg_goal_plan_tasks_updated_at이 공용 public.set_updated_at()(00_base_schema.sql:1432)으로 채운다.';

-- 조회: 주간 계획표(기간 GET) · 오늘 레일(단일 날짜 GET) 둘 다 이 조합을 쓴다.
create index if not exists goal_plan_tasks_profile_date_idx
    on public.goal_plan_tasks (profile_id, plan_date);


-- ---------------------------------------------------------------------
-- (2) RLS — "본인 행 읽기"만 가능(55번:686-696 관례와 동일).
--     클라이언트 write 정책은 두지 않는다 — 쓰기 경로는 service_role을 쓰는
--     api/goal/plan-tasks.js 하나뿐이다.
-- ---------------------------------------------------------------------
alter table public.goal_plan_tasks enable row level security;

drop policy if exists "goal_plan_tasks_select_own" on public.goal_plan_tasks;
create policy "goal_plan_tasks_select_own" on public.goal_plan_tasks
    as permissive for select to authenticated
    using (profile_id = auth.uid());

drop policy if exists "goal_plan_tasks_admin_all" on public.goal_plan_tasks;
create policy "goal_plan_tasks_admin_all" on public.goal_plan_tasks
    as permissive for all to authenticated
    using (public.is_winning_admin())
    with check (public.is_winning_admin());


-- ---------------------------------------------------------------------
-- (3) updated_at 트리거 — 저장소 공용 함수 재사용(00_base_schema.sql:1432
--     public.set_updated_at()). 새 함수를 만들지 않는다.
-- ---------------------------------------------------------------------
drop trigger if exists trg_goal_plan_tasks_updated_at on public.goal_plan_tasks;
create trigger trg_goal_plan_tasks_updated_at
    before update on public.goal_plan_tasks
    for each row execute function public.set_updated_at();


-- =====================================================================
-- 검증용 SELECT (실행 후 수동 확인용 — 주석 해제하고 실행)
-- =====================================================================
-- select table_name from information_schema.tables
--   where table_schema = 'public' and table_name = 'goal_plan_tasks';
--
-- select policyname, cmd from pg_policies
--   where schemaname = 'public' and tablename = 'goal_plan_tasks'
--   order by policyname;
--   -- goal_plan_tasks_admin_all(ALL) / goal_plan_tasks_select_own(SELECT) = 2건
