-- =====================================================================
-- 77_goal_timer_sessions.sql
-- 목표관리(/app/goal) 열공 타이머(#25) 서버 시각 기반 영속화.
-- Supabase SQL Editor / Management API에서 수동 실행 필요.
-- (이 repo에 마이그레이션 러너 없음 — 00~76번과 동일하게 파일 전체를
--  붙여넣고 실행한다.)  idempotent — 여러 번 실행해도 안전.
--
-- 포함:
--   1) public.goal_timer_sessions   과목별 학습 세션(시작~종료 구간)
--   2) RLS — select own + admin select(쓰기는 client 정책 0건, service_role 전용)
--   3) updated_at 트리거(공용 public.set_updated_at() 재사용)
--
-- 배경(임무 지시 "단계 B: 열공 타이머 영속화 + 과목별 목표"):
--  - src/pages/goal/Timer.jsx(:8-11 TODO)는 지금까지 로컬 setInterval mock이었다
--    — 새로고침·탭 이탈에 값이 사라지고, 원본 외부 앱(target)처럼 클라이언트가
--    계산한 초를 그대로 서버가 믿는 구조는 변조 가능하다(브라우저 콘솔에서
--    임의 시간을 조작해 전송할 수 있다). 이 테이블은 "서버 시계가 유일 진실"
--    원칙으로 새로 설계한 신규 기능이다 — target에서 역산할 원본 스키마가
--    없어 컬럼 코멘트에 원본 참조가 없다.
--  - `duration_seconds`는 클라이언트가 보내는 값이 아니라, 세션을 마감하는
--    시점에 서버가 `ended_at - started_at`으로 직접 계산해 채운다
--    (api/goal/timer.js). 진행 중인 세션(`ended_at is null`)은 항상 null이다.
--  - 동시 탭에서 서로 다른 과목을 "시작"해 열린 세션이 2개 이상 생기면 어느
--    쪽이 진짜인지 판정할 수 없다 — partial unique index
--    `(profile_id) where ended_at is null`로 "열린 세션은 학생당 최대 1개"를
--    DB 레벨에서 강제한다. 새 세션을 시작하려면 반드시 기존 열린 세션을
--    먼저 마감(`end_reason='switch'`)해야 하고, 그 마감·insert는
--    api/goal/timer.js가 한 트랜잭션처럼 순서대로 수행한다.
--  - `end_reason`은 세션이 왜 끝났는지 감사 기록이다: 사용자가 직접 멈춤
--    (stop), 다른 과목을 시작해 자동 마감(switch), 자정을 넘겨 서버가
--    분할 마감(midnight — 같은 과목으로 다음날 00:00에 연속 세션을 새로
--    insert한다), 하트비트가 5분 넘게 끊겨 서버가 정리(timeout — 탭을 닫거나
--    기기가 잠들어 stop 요청이 오지 못한 경우의 안전망).
--
-- 의존성:
--   - 00_base_schema.sql : public.is_winning_admin()(1338행),
--                          public.set_updated_at()(1432행)
--   - sql/55_goal_management.sql : public.goal_students(profile_id) FK 대상
--   위 셋만 있으면 다른 마이그레이션과 독립 실행 가능하다.
--   **api/goal/timer.js 배포 전 반드시 선행 실행** — 테이블 없이 배포하면
--   타이머 시작/종료가 전량 실패한다.
--
-- 주의:
--   - admin 판정은 반드시 public.is_winning_admin()을 쓴다(is_admin() 아님,
--     42P17 infinite recursion 회피 — README 「RLS admin 판정」).
--   - 어드민 RLS는 select 전용이다(`for all` 금지) — 75번(goal_plan_tasks)
--     검수 반려 이후의 확정 관례. 이 테이블도 어드민 UI에서 직접 수정할
--     필요가 없다.
--   - `revoke ... from anon, authenticated` 는 걸지 않는다(52번:23-28 근거,
--     55번 헤더 동일 관례).
--   - `force row level security` 도 쓰지 않는다(README:29).
--   - subject는 CHECK 5종('korean'|'math'|'english'|'science'|'etc')이다 —
--     75번(goal_plan_tasks)·goal_subject_targets(78번)과 동일 도메인.
--   - **duration_seconds/started_at/ended_at 어디에도 클라이언트가 보낸
--     시각·초 값을 신뢰·저장하지 않는다.** 전부 서버(api/goal/timer.js)가
--     `now()` 기준으로 계산한다 — 이 파일의 CHECK(0~43200, 최대 12시간)는
--     그 계산이 이미 틀렸을 때의 마지막 방어선일 뿐, 신뢰의 원천이 아니다.
-- =====================================================================


-- ---------------------------------------------------------------------
-- (1) 열공 타이머 세션
--     CHECK 제약은 create table 안에 인라인으로 둔다(43/52/55/75번 관례).
-- ---------------------------------------------------------------------
create table if not exists public.goal_timer_sessions (
    id bigint generated by default as identity primary key,
    profile_id uuid not null references public.goal_students(profile_id) on delete cascade,

    -- 측정 과목. SubjectTimerCard 4장 + 기타 1종(과목 목표는 5종 전부 지원).
    subject text not null,

    -- 이 세션이 속한 날짜(KST, started_at 시점 기준). 서버가 kstYMD(startedAt)로
    -- 채운다 — 자정을 넘겨 계속 진행 중인 세션은 reconcile이 이 값과 오늘(KST)의
    -- 불일치를 감지해 분할 마감하는 트리거 조건으로 쓴다(end_reason='midnight').
    session_date date not null,

    -- 세션 시작 시각. 서버 now() — 클라이언트가 보낸 시각은 쓰지 않는다.
    started_at timestamptz not null,

    -- 세션 종료 시각. null이면 진행 중(= "열린 세션"). 마감 시 서버 now()로 채운다.
    ended_at timestamptz,

    -- 마지막 하트비트 수신 시각. 클라이언트가 60초 간격 + pagehide에서 touch한다.
    -- 스테일 스윕(now - coalesce(last_heartbeat_at, started_at) > 5분)이 열린
    -- 세션을 강제 마감(end_reason='timeout')할지 판단하는 기준이다.
    last_heartbeat_at timestamptz,

    -- 세션 길이(초). 진행 중(ended_at is null)이면 항상 null — 서버가 마감
    -- 시점에 ended_at - started_at으로 1회 계산해 채우고 그 뒤로 바꾸지 않는다.
    -- 상한 43200(12시간)은 방어적 캡: reconcile 스테일 스윕이 놓친 극단값이
    -- 하루 누적 통계를 오염시키는 것을 막는다.
    duration_seconds integer
        check (duration_seconds is null or duration_seconds between 0 and 43200),

    -- 세션이 끝난 사유. 진행 중이면 null. api/goal/timer.js가 채운다.
    end_reason text
        check (end_reason is null or end_reason in ('stop', 'switch', 'midnight', 'timeout')),

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint goal_timer_sessions_subject_check
        check (subject in ('korean', 'math', 'english', 'science', 'etc')),
    -- 진행 중/마감 상태 일관성: 열린 세션은 ended_at·duration_seconds·end_reason이
    -- 전부 비어 있어야 하고, 마감된 세션은 셋 다 채워져 있어야 한다.
    constraint goal_timer_sessions_open_state_check
        check (
            (ended_at is null and duration_seconds is null and end_reason is null)
            or
            (ended_at is not null and duration_seconds is not null and end_reason is not null)
        )
);

comment on table public.goal_timer_sessions is
    '목표관리 열공 타이머(#25) 과목별 학습 세션. 원본 외부 앱(target)에 대응 스키마 없음(신규 기능, 서버 시각 기반으로 새로 설계) — 클라이언트가 초를 계산해 보내던 원본 구조는 변조 가능해 이식하지 않았다. 쓰기는 service_role(api/goal/timer.js)만. sql/77_goal_timer_sessions.sql 참고.';

comment on column public.goal_timer_sessions.profile_id is
    'goal_students.profile_id(≡auth.users.id). 소유자 판정은 언제나 세션 토큰에서 얻은 profileId로만 한다(api/_lib/goalRepo.js openGoalSession 관례) — 클라이언트가 보낸 어떤 id도 신뢰하지 않는다.';
comment on column public.goal_timer_sessions.subject is
    '과목 코드 5종. 한글 라벨(국어/수학/영어/탐구/기타)과의 매핑은 api/_lib/goalRepo.js SUBJECT_CODE_TO_LABEL/SUBJECT_LABEL_TO_CODE가 담당한다 — DB에는 코드값만 저장한다.';
comment on column public.goal_timer_sessions.session_date is
    '이 세션이 속한 KST 날짜. started_at으로부터 서버가 파생해 저장한다(파생값이지만 자정 분할 reconcile의 판정 기준이라 정규 컬럼으로 둔다).';
comment on column public.goal_timer_sessions.started_at is
    '세션 시작 시각(서버 now()). 클라이언트가 보낸 시각은 어디서도 신뢰하지 않는다.';
comment on column public.goal_timer_sessions.ended_at is
    '세션 종료 시각. null = 진행 중("열린 세션"). partial unique index(아래 (2))로 학생당 동시에 최대 1개만 존재하도록 강제한다.';
comment on column public.goal_timer_sessions.last_heartbeat_at is
    '마지막 하트비트 시각. 프론트 60초 setInterval + pagehide(navigator.sendBeacon)가 touch한다. 스테일 스윕이 5분 초과 시 timeout 마감의 종료 시각으로 이 값(없으면 started_at)을 쓴다.';
comment on column public.goal_timer_sessions.duration_seconds is
    '세션 길이(초). 진행 중이면 null, 마감되면 ended_at - started_at을 서버가 1회 계산해 채운다. 상한 43200(12시간)은 스테일 세션 방어 캡.';
comment on column public.goal_timer_sessions.end_reason is
    '마감 사유. stop=사용자 직접 종료, switch=다른 과목 시작으로 자동 마감, midnight=자정 경계 서버 분할 마감(같은 과목으로 다음날 00:00 세션이 이어서 insert된다), timeout=하트비트 5분 초과 스테일 스윕.';
comment on column public.goal_timer_sessions.created_at is
    '행 생성 시각.';
comment on column public.goal_timer_sessions.updated_at is
    '마지막 갱신 시각(하트비트 touch 포함). 트리거 trg_goal_timer_sessions_updated_at이 공용 public.set_updated_at()(00_base_schema.sql:1432)으로 채운다.';

-- (2) 열린 세션 유일성 — 학생당 진행 중인 세션은 언제나 최대 1개.
--     동시 탭에서 서로 다른 과목을 "시작"해도 DB가 2번째 insert를 23505로
--     거부한다(api/goal/timer.js가 그 오류를 잡아 기존 세션을 마감 후 1회
--     재시도한다).
create unique index if not exists goal_timer_sessions_open_unique
    on public.goal_timer_sessions (profile_id)
    where ended_at is null;

-- 조회: GET(오늘 날짜 과목별 합계)이 이 조합을 쓴다.
create index if not exists goal_timer_sessions_profile_date_idx
    on public.goal_timer_sessions (profile_id, session_date);


-- ---------------------------------------------------------------------
-- (3) RLS — "본인 행 읽기"만 가능(55번:686-696 관례와 동일).
--     클라이언트 write 정책은 두지 않는다 — 쓰기 경로는 service_role을 쓰는
--     api/goal/timer.js 하나뿐이다. 어드민 정책도 select 전용이다
--     (goal_timer_sessions_admin_select) — `for all + with check`는 어드민
--     세션에도 쓰기를 열어 "쓰기는 service_role 전용" 원칙을 어긴다
--     (55번:706-716 goal_students_admin_all과 달리, 이 테이블은 어드민
--     UI에서 직접 수정할 필요가 없어 select만으로 충분하다 — 75번 검수
--     반려 반영).
-- ---------------------------------------------------------------------
alter table public.goal_timer_sessions enable row level security;

drop policy if exists "goal_timer_sessions_select_own" on public.goal_timer_sessions;
create policy "goal_timer_sessions_select_own" on public.goal_timer_sessions
    as permissive for select to authenticated
    using (profile_id = auth.uid());

drop policy if exists "goal_timer_sessions_admin_all" on public.goal_timer_sessions;
drop policy if exists "goal_timer_sessions_admin_select" on public.goal_timer_sessions;
create policy "goal_timer_sessions_admin_select" on public.goal_timer_sessions
    as permissive for select to authenticated
    using (public.is_winning_admin());


-- ---------------------------------------------------------------------
-- (4) updated_at 트리거 — 저장소 공용 함수 재사용(00_base_schema.sql:1432
--     public.set_updated_at()). 새 함수를 만들지 않는다.
-- ---------------------------------------------------------------------
drop trigger if exists trg_goal_timer_sessions_updated_at on public.goal_timer_sessions;
create trigger trg_goal_timer_sessions_updated_at
    before update on public.goal_timer_sessions
    for each row execute function public.set_updated_at();


-- =====================================================================
-- 검증용 SELECT (실행 후 수동 확인용 — 주석 해제하고 실행)
-- =====================================================================
-- select table_name from information_schema.tables
--   where table_schema = 'public' and table_name = 'goal_timer_sessions';
--
-- select policyname, cmd from pg_policies
--   where schemaname = 'public' and tablename = 'goal_timer_sessions'
--   order by policyname;
--   -- goal_timer_sessions_admin_select(SELECT) / goal_timer_sessions_select_own(SELECT) = 2건
--
-- select indexname from pg_indexes
--   where schemaname = 'public' and tablename = 'goal_timer_sessions'
--   order by indexname;
--   -- goal_timer_sessions_open_unique / goal_timer_sessions_pkey / goal_timer_sessions_profile_date_idx
