-- =====================================================================
-- 79_goal_mentor_comments.sql
-- 목표관리(/app/goal) 성장 리포트(#33/#34) 멘토 코멘트 카드 저장소.
-- Supabase SQL Editor / Management API에서 수동 실행 필요.
-- (이 repo에 마이그레이션 러너 없음 — 접두어가 곧 수동 실행 순서다.)
-- idempotent — 여러 번 실행해도 안전.
--
-- 포함:
--   1) public.goal_mentor_comments   기간(주/월)별 멘토 코멘트 1건
--   2) RLS — select own + admin select(쓰기는 client 정책 0건, 이번 단계는 읽기 UI만)
--   3) updated_at 트리거(공용 public.set_updated_at() 재사용)
--
-- 배경(임무 지시 "I: 리포트 3종 구현" §D10):
--   리포트 최하단 MentorCommentCard(GrowthReportBody.jsx)는 지금까지
--   goalReportMock.js의 고정 문장을 그대로 렌더했다. 실배선을 위해 기간(주간/월간)
--   단위로 코멘트 1건을 저장할 테이블이 필요하다. 쓰기 어드민 UI(멘토가 코멘트를
--   입력하는 화면)는 이번 범위 밖이다(팀장 지시 "쓰기 어드민 UI는 후속 — 이번엔
--   read만") — 이 마이그레이션은 스키마·RLS만 만들고, api/goal/report.js는 select만
--   한다. 행이 없으면(멘토가 아직 안 썼으면) 리포트가 멘토 카드 자체를 렌더하지
--   않는다(GrowthReportBody.jsx 조건부 렌더 — 빈 카드를 보여주지 않는다).
--
--   period_key 는 팀장 확정 "순수 달력" 경계를 그대로 쓴다 — 주간은 그 주 월요일
--   YMD('2026-08-03'), 월간은 'YYYY-MM'('2026-08')이다. src/lib/goal/report/aggregate.js
--   resolveWeeklyPeriod/resolveMonthlyPeriod 의 periodKey 와 글자 단위로 같은 값이라야
--   조회가 맞아떨어진다 — 이 값을 임의로 재구성(예: ISO week number)하지 않는다.
--
-- 의존성:
--   - 00_base_schema.sql : public.is_winning_admin()(1338행), public.set_updated_at()(1432행)
--   - sql/55_goal_management.sql : public.goal_students(profile_id) FK 대상
--   위 셋만 있으면 다른 마이그레이션과 독립 실행 가능하다.
--   api/goal/report.js 는 이 테이블이 없어도 500 이 아니라 멘토 카드만 빠진 리포트를
--   낸다(PostgREST 42P01 을 잡아 빈 값으로 접는 방어 코드가 없다면 — 배포 순서는
--   반드시 이 파일을 먼저 적용한다).
--
-- 주의:
--   - admin 판정은 반드시 public.is_winning_admin()을 쓴다(is_admin() 아님).
--   - 어드민 RLS는 select 전용이다(`for all` 금지) — sql/75(goal_plan_tasks) 검수
--     반려 이후의 확정 관례(sql/77_goal_timer_sessions.sql 헤더에도 동일 반영).
--     쓰기 어드민 UI가 생기기 전까지 이 원칙을 유지한다 — 지금 `for all`을 열면
--     "쓰기는 service_role 전용" 원칙이 먼저 깨진 채로 남는다.
--   - `revoke ... from anon, authenticated` 는 걸지 않는다(52번:23-28 근거,
--     55번 헤더 동일 관례).
--   - `force row level security` 도 쓰지 않는다(README:29).
--   - body 길이 CHECK(~2000자)는 리포트 카드가 무한정 늘어나는 것을 막는 방어적 상한이다
--     (UI 카피 예산과 무관 — 실제 멘토 코멘트 입력 UI가 생기면 그쪽에서 별도로 더 좁은
--     상한을 둘 수 있다).
-- =====================================================================


-- ---------------------------------------------------------------------
-- (1) 멘토 코멘트
-- ---------------------------------------------------------------------
create table if not exists public.goal_mentor_comments (
    id bigint generated by default as identity primary key,
    profile_id uuid not null references public.goal_students(profile_id) on delete cascade,

    -- 리포트 종류. 학습방향 리포트(#37/#38)는 이번 범위 밖 — 성장 리포트 2종만 다룬다.
    period_type text not null
        check (period_type in ('weekly', 'monthly')),

    -- 기간 키. weekly='그 주 월요일 YMD', monthly='YYYY-MM' — aggregate.js
    -- resolveWeeklyPeriod/resolveMonthlyPeriod 의 periodKey 와 동일 규약(팀장 확정
    -- "순수 달력" 경계, 위 배경 절 참고). 형식 검증은 CHECK 정규식으로 방어한다.
    period_key text not null
        check (
            (period_type = 'weekly' and period_key ~ '^\d{4}-\d{2}-\d{2}$')
            or
            (period_type = 'monthly' and period_key ~ '^\d{4}-\d{2}$')
        ),

    body text not null
        check (char_length(body) between 1 and 2000),

    -- 작성 시각. 리포트 카드의 "YYYY-MM-DD 작성" 표기(dateLabel)가 이 값을 KST로 자른다.
    written_at timestamptz not null default now(),

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    -- 기간당 코멘트는 1건 — 같은 기간에 재작성하면 update(upsert)로 덮어쓴다.
    constraint goal_mentor_comments_period_key unique (profile_id, period_type, period_key)
);

comment on table public.goal_mentor_comments is
    '목표관리 성장 리포트(#33/#34) 멘토 코멘트. 기간(주/월)당 1건, upsert 대상. 쓰기 어드민 UI는 후속 — 이번 단계는 api/goal/report.js 의 select 전용. sql/79_goal_mentor_comments.sql 참고.';
comment on column public.goal_mentor_comments.profile_id is
    'goal_students.profile_id(≡auth.users.id). 소유자 판정은 언제나 세션 토큰에서 얻은 profileId 로만 한다(api/_lib/goalRepo.js openGoalSession 관례).';
comment on column public.goal_mentor_comments.period_type is
    '리포트 종류. weekly=주간 성장 리포트(#33), monthly=월간 성장 리포트(#34). 학습방향 리포트(#37/#38)는 다루지 않는다.';
comment on column public.goal_mentor_comments.period_key is
    '기간 키 — weekly는 그 주 월요일 YMD, monthly는 YYYY-MM. src/lib/goal/report/aggregate.js resolveWeeklyPeriod/resolveMonthlyPeriod 의 periodKey 와 글자 단위로 같아야 조회가 맞는다(가상 주차·ISO 주차 아님, 순수 달력).';
comment on column public.goal_mentor_comments.body is
    '코멘트 본문. 1~2000자 방어적 상한(리포트 카드가 무한정 늘어나는 것을 막는다).';
comment on column public.goal_mentor_comments.written_at is
    '작성 시각. 리포트 카드의 "YYYY-MM-DD 작성" 표기가 이 값을 KST로 잘라 쓴다.';
comment on column public.goal_mentor_comments.updated_at is
    '마지막 갱신 시각. 트리거 trg_goal_mentor_comments_updated_at 이 공용 public.set_updated_at()(00_base_schema.sql:1432)으로 채운다.';


-- ---------------------------------------------------------------------
-- (2) RLS — "본인 행 읽기"만 가능. 클라이언트 write 정책은 두지 않는다
--     (쓰기 어드민 UI가 생기기 전까지 쓰기 경로 자체가 없다). 어드민도
--     select 전용이다(`for all` 금지 — sql/75/77 검수 반려 반영, 위 "주의" 절 참고).
-- ---------------------------------------------------------------------
alter table public.goal_mentor_comments enable row level security;

drop policy if exists "goal_mentor_comments_select_own" on public.goal_mentor_comments;
create policy "goal_mentor_comments_select_own" on public.goal_mentor_comments
    as permissive for select to authenticated
    using (profile_id = auth.uid());

drop policy if exists "goal_mentor_comments_admin_all" on public.goal_mentor_comments;
drop policy if exists "goal_mentor_comments_admin_select" on public.goal_mentor_comments;
create policy "goal_mentor_comments_admin_select" on public.goal_mentor_comments
    as permissive for select to authenticated
    using (public.is_winning_admin());


-- ---------------------------------------------------------------------
-- (3) updated_at 트리거 — 저장소 공용 함수 재사용(00_base_schema.sql:1432
--     public.set_updated_at()). 새 함수를 만들지 않는다.
-- ---------------------------------------------------------------------
drop trigger if exists trg_goal_mentor_comments_updated_at on public.goal_mentor_comments;
create trigger trg_goal_mentor_comments_updated_at
    before update on public.goal_mentor_comments
    for each row execute function public.set_updated_at();


-- =====================================================================
-- 검증용 SELECT (실행 후 수동 확인용 — 주석 해제하고 실행)
-- =====================================================================
-- select table_name from information_schema.tables
--   where table_schema = 'public' and table_name = 'goal_mentor_comments';
--
-- select policyname, cmd from pg_policies
--   where schemaname = 'public' and tablename = 'goal_mentor_comments'
--   order by policyname;
--   -- goal_mentor_comments_admin_select(SELECT) / goal_mentor_comments_select_own(SELECT) = 2건
--
-- select conname from pg_constraint
--   where conrelid = 'public.goal_mentor_comments'::regclass
--   order by conname;
--   -- goal_mentor_comments_period_key(UNIQUE) 포함 확인
